webFrontend:
    image: kommunalcrowd/iojs-dev:0.2
    links:
        - db
    command: bash
    ports:
        - "1337:1337"
    volumes:
        - /srv/source:/src
        - /logs:/logs
db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: 12345
